---
title: "Homework3"
author: "Isabel Nelson"
date: "10/6/2020"
output: github_document
---

```{r setup, include=FALSE}
library(p8105.datasets)
library(tidyverse)

# Set how graphs are printed in knitted file
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

#Set global theme for plots
theme_set(theme_minimal() + theme(legend.position = "bottom"))

#Set options for all plots
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

#Set options for all plots
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1 

```{r}
data("instacart")
```

The dataset instacart contains `r nrow(instacart)` observations and `r ncol(instacart)` columns. Observations are at the level of items in orders placed by users. The variables provide information about the users/orders and the items purchased. The total list of variables is: `r colnames(instacart)`. 


## Problem 2


## Problem 3
